name: monexo
description:
  A simple money management app for those who want to be in control of their
  financial life.

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter

  after_layout: ^1.2.0
  cloud_firestore: ^5.6.6
  #  collection: ^1.19.1
  encrypt: ^5.0.3
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.2.2
  http: ^1.3.0
  intl: ^0.19.0
  local_auth: ^2.0.1
  package_info: ^2.0.2
  path: ^1.9.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  transparent_image: ^2.0.1
  url_launcher: ^6.3.1
  fl_chart: 0.69.0

dev_dependencies:
  build_runner: ^2.4.13


flutter_intl:
  enabled: true
  main_locale: uk
  arb_dir: lib/l10n

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/data/
    - assets/categories/
    - assets/categories/expense/
    - assets/categories/income/
    - assets/categories/custom/
